// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMc3acwds_jkuA7QX8Dpw7FNjCVyFWNTQ',
    appId: '1:58113713926:web:0b2681458730d402e0a087',
    messagingSenderId: '58113713926',
    projectId: 'socialmediafeedapp-80e76',
    authDomain: 'socialmediafeedapp-80e76.firebaseapp.com',
    storageBucket: 'socialmediafeedapp-80e76.appspot.com',
    measurementId: 'G-4B4G3L69RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnhGDT3E5XG8gPMcHyeQGTJX340i-xe9s',
    appId: '1:58113713926:android:731c3ce5ecc2ecaae0a087',
    messagingSenderId: '58113713926',
    projectId: 'socialmediafeedapp-80e76',
    storageBucket: 'socialmediafeedapp-80e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7s2citYfiUv7_KqGKldKtbGQv5XgNR2U',
    appId: '1:58113713926:ios:e40c946da274ab28e0a087',
    messagingSenderId: '58113713926',
    projectId: 'socialmediafeedapp-80e76',
    storageBucket: 'socialmediafeedapp-80e76.appspot.com',
    iosBundleId: 'com.example.socialmediafeedapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7s2citYfiUv7_KqGKldKtbGQv5XgNR2U',
    appId: '1:58113713926:ios:6879b74a897c839be0a087',
    messagingSenderId: '58113713926',
    projectId: 'socialmediafeedapp-80e76',
    storageBucket: 'socialmediafeedapp-80e76.appspot.com',
    iosBundleId: 'com.example.socialmediafeedapp.RunnerTests',
  );
}
